rm -rf javascript_alt/*
mkdir -p javascript_alt
cp javascript/alt2.html javascript_alt/index.html
cp javascript/index.html javascript_alt/alt1.html
cp javascript/manifest.json javascript_alt/manifest_alt2.json
cp javascript/manifest_alt1.json javascript_alt/manifest.json
cp javascript/icon.png javascript_alt/icon.png
cp javascript/classes.js javascript_alt/classes.js
cp javascript/Minecraft4k_alt2.html javascript_alt/4k.html