"use strict";
(function(module){if(typeof define==='function'&&define.amd){define(['exports'],function(exports){module(exports);});}else if(typeof exports==='object'&&exports!==null&&typeof exports.nodeName!=='string'){module(exports);}else{module(typeof self!=='undefined'?self:this);}}(function(B){let Da=2463534242,Eh=()=>{let x=Da;x^=x<<13;x^=x>>>17;x^=x<<5;Da=x;return x;},B2=f=>function(){return f(this);},CS=f=>function(p1){return f(this,p1);},DG=f=>function(){let args=Array.prototype.slice.apply(arguments);C8(function()
{f.apply(this,args);});},DE=f=>(args,callback)=>{if(!args){args=[];}let javaArgs=BK(Bc(),args.length);for(let i=0;i<args.length;++i){javaArgs.data[i]=Bm(args[i]);}C8(()=>{f.call(null,javaArgs);},callback);},CN=target=>target.$clinit=()=>{},EH=obj=>{let cls=obj.constructor;let arrayDegree=0;while(cls.$meta&&cls.$meta.item){++arrayDegree;cls=cls.$meta.item;}let clsName="";if(cls.$meta.primitive){clsName=cls.$meta.name;}else {clsName=cls.$meta?cls.$meta.name||"a/"+cls.name:"@"+cls.name;}while(arrayDegree-->0){clsName
+="[]";}return clsName;},E=superclass=>{if(superclass===0){return function(){};}if(superclass===void 0){superclass=Bc();}return function(){superclass.call(this);};},BG=cls=>Em(cls),Bc=()=>D,CO=()=>{{return Dy();}},BI=t=>{{return Dj(t);}},W=f=>function(){return f.apply(null,[this].concat(Array.prototype.slice.call(arguments)));},EO=()=>{return {$array:null,classObject:null,$meta:{supertypes:[],superclass:null}};},BJ=(name,binaryName)=>{let cls=EO();cls.$meta.primitive=true;cls.$meta.name=name;cls.$meta.binaryName
=binaryName;cls.$meta.enum=false;cls.$meta.item=null;cls.$meta.simpleName=null;cls.$meta.declaringClass=null;cls.$meta.enclosingClass=null;return cls;},EZ=BJ("boolean","Z"),BX=BJ("char","C"),Cp=BJ("int","I"),Ed=BJ("double","D"),Y=(a,b)=>a>b?1:a<b? -1:a===b?0:1,M=Math.imul||function(a,b){let ah=a>>>16&0xFFFF;let al=a&0xFFFF;let bh=b>>>16&0xFFFF;let bl=b&0xFFFF;return al*bl+(ah*bl+al*bh<<16>>>0)|0;},Dg=BigInt(0),Ba=val=>BigInt.asIntN(64,BigInt(val|0)),Bi=val=>BigInt.asIntN(64,BigInt(val>=0?Math.floor(val):Math.ceil(val))),Bk
=val=>Number(BigInt.asIntN(32,val))|0,Ct=(a,b)=>a>b,DH=(a,b)=>a>=b,C3=(a,b)=>BigInt.asIntN(64,a+b),CW=(a,b)=>BigInt.asIntN(64,a -b),BK=(cls,sz)=>{let data=new Array(sz);data.fill(null);return new (Bs(cls))(data);},BA=sz=>new EF(new Uint16Array(sz)),Bp=sz=>new De(new Int32Array(sz)),BN=data=>{let buffer=new Int32Array(data.length);buffer.set(data);return new De(buffer);},ES=sz=>new Ea(new Int8Array(sz)),DO=sz=>new Et(new Float64Array(sz)),Bs=cls=>{let result=cls.$array;if(result===null){function JavaArray(data)
{(Bc()).call(this);this.data=data;}JavaArray.prototype=Object.create((Bc()).prototype);JavaArray.prototype.type=cls;JavaArray.prototype.constructor=JavaArray;JavaArray.prototype.toString=function(){let str="[";for(let i=0;i<this.data.length;++i){if(i>0){str+=", ";}str+=this.data[i].toString();}str+="]";return str;};JavaArray.prototype.b8=function(){let dataCopy;if('slice' in this.data){dataCopy=this.data.slice();}else {dataCopy=new this.data.constructor(this.data.length);for(let i=0;i<dataCopy.length;++i){dataCopy[i]
=this.data[i];}}return new (Bs(this.type))(dataCopy);};let name="["+cls.$meta.binaryName;JavaArray.$meta={item:cls,supertypes:[Bc()],primitive:false,superclass:Bc(),name:name,binaryName:name,enum:false,simpleName:null,declaringClass:null,enclosingClass:null};JavaArray.classObject=null;JavaArray.$array=null;result=JavaArray;cls.$array=JavaArray;}return result;},Cg,Ey=strings=>{Fb();Cg=new Array(strings.length);for(let i=0;i<strings.length;++i){Cg[i]=C4(Bm(strings[i]));}},J=index=>Cg[index],Cd=(array,offset,count)=>
{let result="";let limit=offset+count;for(let i=offset;i<limit;i=i+1024|0){let next=Math.min(limit,i+1024|0);result+=String.fromCharCode.apply(null,array.subarray(i,next));}return result;},Bm=str=>str===null?null:D8(str),BL=str=>str===null?null:str.bg,Fb=()=>(()=>{})(),C4;
{C4=str=>str;}let S=ex=>{throw Cr(ex);},Bw=Symbol("javaException"),Cr=ex=>{if(!ex.$jsException){X(ex);}return ex.$jsException;},X=ex=>{let javaCause=E7(ex);let jsCause=javaCause!==null?javaCause.$jsException:void 0;let cause=typeof jsCause==="object"?{cause:jsCause}:void 0;let err=new Bd("Java exception thrown",cause);if(typeof Error.captureStackTrace==="function"){Error.captureStackTrace(err);}err[Bw]=ex;ex.$jsException=err;CX(err,ex);},CX=(err,ex)=>{if(typeof D4==="function"&&err.stack){let stack=D4(err.stack);let javaStack
=BK(Er(),stack.length);let elem;let noStack=false;for(let i=0;i<stack.length;++i){let element=stack[i];elem=ED(Bm(element.className),Bm(element.methodName),Bm(element.fileName),element.lineNumber);if(elem==null){noStack=true;break;}javaStack.data[i]=elem;}if(!noStack){EW(ex,javaStack);}}},Bd;
if(typeof Reflect==='object'){let defaultMessage=Symbol("defaultMessage");Bd=function Bd(message,cause){let self=Reflect.construct(Error,[void 0,cause],Bd);Object.setPrototypeOf(self,Bd.prototype);self[defaultMessage]=message;return self;}
;Bd.prototype=Object.create(Error.prototype,{constructor:{configurable:true,writable:true,value:Bd},message:{get(){try {let javaException=this[Bw];if(typeof javaException==='object'){let javaMessage=Du(javaException);if(typeof javaMessage==="object"){return javaMessage!==null?javaMessage.toString():null;}}return this[defaultMessage];}catch(e){return "Exception occurred trying to extract Java exception message: "+e;}}}});}else {Bd=Error;}let DM=e=>e instanceof Error&&typeof e[Bw]==='object'?e[Bw]:null,H=err=>
{let ex=err[Bw];if(!ex){ex=DZ(Bm("(JavaScript) "+err.toString()));err[Bw]=ex;ex.$jsException=err;CX(err,ex);}return ex;},DZ=message=>Eo(message),Du=t=>E1(t),E7=t=>Fa(t),Er=()=>Bc(),ED=(className,methodName,fileName,lineNumber)=>{{return null;}},EW=(e,stack)=>{},CP=null,Dw=data=>{let i=0;let packages=new Array(data.length);for(let j=0;j<data.length;++j){let prefixIndex=data[i++];let prefix=prefixIndex>=0?packages[prefixIndex]:"";packages[j]=prefix+data[i++]+".";}CP=packages;},CV=data=>{let packages=CP;let i=
0;while(i<data.length){let cls=data[i++];cls.$meta={};let m=cls.$meta;let className=data[i++];m.name=className!==0?className:null;if(m.name!==null){let packageIndex=data[i++];if(packageIndex>=0){m.name=packages[packageIndex]+m.name;}}m.binaryName="L"+m.name+";";let superclass=data[i++];m.superclass=superclass!==0?superclass:null;m.supertypes=data[i++];if(m.superclass){m.supertypes.push(m.superclass);cls.prototype=Object.create(m.superclass.prototype);}else {cls.prototype={};}let flags=data[i++];m.enum=(flags
&8)!==0;m.flags=flags;m.primitive=false;m.item=null;cls.prototype.constructor=cls;cls.classObject=null;m.accessLevel=data[i++];let innerClassInfo=data[i++];if(innerClassInfo===0){m.simpleName=null;m.declaringClass=null;m.enclosingClass=null;}else {let enclosingClass=innerClassInfo[0];m.enclosingClass=enclosingClass!==0?enclosingClass:null;let declaringClass=innerClassInfo[1];m.declaringClass=declaringClass!==0?declaringClass:null;let simpleName=innerClassInfo[2];m.simpleName=simpleName!==0?simpleName:null;}let clinit
=data[i++];cls.$clinit=clinit!==0?clinit:function(){};let virtualMethods=data[i++];if(virtualMethods!==0){for(let j=0;j<virtualMethods.length;j+=2){let name=virtualMethods[j];let func=virtualMethods[j+1];if(typeof name==='string'){name=[name];}for(let k=0;k<name.length;++k){cls.prototype[name[k]]=func;}}}cls.$array=null;}};
function Q(runner){this.status=3;this.stack=[];this.suspendCallback=null;this.runner=runner;this.attribute=null;this.completeCallback=null;}
Q.prototype.push=function(){for(let i=0;i<arguments.length;++i){this.stack.push(arguments[i]);}return this;};Q.prototype.s=Q.prototype.push;Q.prototype.pop=function(){return this.stack.pop();};Q.prototype.l=Q.prototype.pop;Q.prototype.isResuming=function(){return this.status===2;};Q.prototype.isSuspending=function(){return this.status===1;};Q.prototype.suspend=function(callback){this.suspendCallback=callback;this.status=1;};Q.prototype.start=function(callback){if(this.status!==3){throw new Error("Thread already started");}if
(BE!==null){throw new Error("Another thread is running");}this.status=0;this.completeCallback=callback?callback:result=>{if(result instanceof Error){throw result;}};this.run();};Q.prototype.resume=function(){if(BE!==null){throw new Error("Another thread is running");}this.status=2;this.run();};Q.prototype.run=function(){BE=this;let result;try {result=this.runner();}catch(e){result=e;}finally {BE=null;}if(this.suspendCallback!==null){let self=this;let callback=this.suspendCallback;this.suspendCallback=null;callback(()=>
self.resume());}else if(this.status===0){this.completeCallback(result);}};let T=()=>{let thread=K();return thread!=null&&thread.isSuspending();},Bh=()=>{let thread=K();return thread!=null&&thread.isResuming();},Cx=()=>{let nativeThread=K();if(nativeThread===null){throw new Error("Suspension point reached from non-threading context "+"(perhaps, from native JS method). See https://teavm.org/docs/runtime/coroutines.html "+"('Interaction with JavaScript' section)");}return nativeThread;},C8=(runner,callback)=>(new Q(runner)).start(callback),BE
=null,K=()=>BE,Bf=()=>{throw new Error("Invalid recorded state");};
function D(){this.bi=null;this.$id$=0;}
let Fn=b=>{let c,d;c=F;if(c===null)return;if(b.bi===null){d=new BM;d.bh=c;b.bi=d;}b=b.bi;d=b.bh;if(d===null)b.bh=c;else if(d!==c){d=new Cz;X(d);d.bn=1;d.bm=1;d.bF=J(0);S(d);}b.bk=b.bk+1|0;},Fh=b=>{let c,d;if(F===null)return;if(!BD(b)){c=b.bi;if(c.bh===F){d=c.bk-1|0;c.bk=d;if(!d)c.bh=null;BD(b);return;}}b=new BQ;X(b);b.bn=1;b.bm=1;S(b);},BW=b=>{let c,$p,$z;$p=0;if(Bh()){let $T=K();$p=$T.l();c=$T.l();b=$T.l();}_:while(true){switch($p){case 0:c=1;$p=1;case 1:EL(b,c);if(T()){break _;}return;default:Bf();}}K().s(b,
c,$p);},EL=(b,c)=>{let d,$p,$z;$p=0;if(Bh()){let $T=K();$p=$T.l();d=$T.l();c=$T.l();b=$T.l();}_:while(true){switch($p){case 0:if(b.bi===null){d=new BM;d.bh=F;b.bi=d;}d=b.bi;if(d.bh===null)d.bh=F;if(d.bh===F){d.bk=d.bk+c|0;return;}$p=1;case 1:DC(b,c);if(T()){break _;}return;default:Bf();}}K().s(b,c,d,$p);},Ew=(b,c,d)=>{let e,f,g;e=F;f=b.bi;if(f===null){f=new BM;f.bh=e;b.bi=f;if(e!==e)F=e;F.bo=U();b=b.bi;b.bk=b.bk+c|0;b=null;d.bu.e(b);return;}if(f.bh===null){f.bh=e;if(e!==e)F=e;F.bo=U();b=b.bi;b.bk=b.bk+c|0;b
=null;d.bu.e(b);return;}if(f.bq===null)f.bq=DP();f=f.bq;g=new Db;g.bN=e;g.bO=b;g.bL=c;g.bM=d;d=g;f.push(d);},Br=b=>{EM(b,1);},EM=(b,c)=>{let d;if(!BD(b)){d=b.bi;if(d.bh===F){c=d.bk-c|0;d.bk=c;if(c>0)return;d.bh=null;d=d.bq;if(d!==null&&!(d.length?0:1)){d=new CB;d.bJ=b;Ca(d,0);}else BD(b);return;}}b=new BQ;X(b);b.bn=1;b.bm=1;S(b);},D_=b=>{let c,d,e;if(!BD(b)){c=b.bi;if(c.bh===null){b=c.bq;if(b!==null&&!(b.length?0:1)){b=c.bq.shift();if(b!==null&&!(b instanceof Bc()))b=CC(b);d=b;c.bq=null;b=d;c=b.bN;d=b.bO;e=
b.bL;b=b.bM;if(F!==c)F=c;F.bo=U();d=d.bi;d.bh=c;d.bk=d.bk+e|0;c=null;b.bu.e(c);}return;}}},BD=a=>{let b,c;b=a.bi;if(b===null)return 1;a:{if(b.bh===null){c=b.bq;if(!(c!==null&&!(c.length?0:1))){b=b.bI;if(b===null)break a;if(b.length?0:1)break a;}}return 0;}a.bi=null;return 1;},En=a=>{return;},E6=()=>{let a=new D();En(a);return a;},EP=a=>{let b,c,d,e,f,g,h,i,j;b=a;if(!b.$id$)b.$id$=Eh();c=Ek(a.$id$,4);b=new CZ;b.bs=BA(16);d=b.bp;e=b;f=J(1);e=e;Cy(e,d,f);Cy(e,b.bp,c===null?J(2):c);f=new O;g=b.bs;h=g.data;i=b.bp;j
=h.length;if(i>=0&&i<=(j-0|0)){f.bg=Cd(g.data,0,i);return f;}b=new BU;D$(b);b.bn=1;b.bm=1;EV(b);S(b);},Cn=a=>{let b,c;b=a.bi;if(!(b!==null&&b.bh===F?1:0)){b=new BQ;X(b);b.bn=1;b.bm=1;S(b);}b=b.bI;if(b===null)return;while(!(b.length?0:1)){c=b.shift();if(c!==null&&!(c instanceof Bc()))c=CC(c);c=c;if(!c.n())Ca(c,0);}a.bi.bI=null;},DC=(b,c)=>{let thread=Cx();let javaThread=CO();if(thread.isResuming()){thread.status=0;let result=thread.attribute;if(result instanceof Error){throw result;}return result;}let callback
=function(){};callback.e=val=>{thread.attribute=val;BI(javaThread);thread.resume();};callback.be=e=>{thread.attribute=Cr(e);BI(javaThread);thread.resume();};callback=Dd(callback);thread.suspend(()=>{try {Ew(b,c,callback);;}catch($e){callback.be($e);}});return null;},Cs=E(0),CM=E(0);
function CL(){D.call(this);this.b7=null;}
let Em=b=>{let c;if(b===null)return null;c=b.classObject;if(c===null){c=new CL;c.b7=b;b.classObject=c;}return c;},Ec=E(),V=(b,c)=>{let name='jso$functor$'+c;let result=b[name];if(typeof result!=='function'){let fn=function(){return b[c].apply(b,arguments);};result=()=>fn;b[name]=result;}return result();},EN=E(),Fe=b=>{setTimeout(()=>{DG(Dk)(b);},0);},Dk=b=>{let $p,$z;$p=0;if(Bh()){let $T=K();$p=$T.l();b=$T.l();}_:while(true){switch($p){case 0:$p=1;case 1:b.o();if(T()){break _;}return;default:Bf();}}K().s(b,
$p);},Ca=(b,c)=>{setTimeout(()=>{Dk(b);},c);},DP=()=>{return [];};
function By(){let a=this;D.call(a);a.bF=null;a.b3=null;a.bn=0;a.bm=0;}
let EV=a=>{return a;},D$=a=>{X(a);},E1=a=>{return a.bF;},Fa=a=>{let b;b=a.b3;if(b===a)b=null;return b;},I=E(By),R=E(I),DS=(a,b)=>{X(a);a.bn=1;a.bm=1;a.bF=b;},Eo=a=>{let b=new R();DS(b,a);return b;},E8=E(R),Bz=E(0),BT=E(0),Cb=E(0),O=E(),CF=null,C$=null,C1=null,DF=(a,b)=>{a.bg=Cd(b.data,0,b.data.length);},Fi=a=>{let b=new O();DF(b,a);return b;},Eg=(a,b)=>{a.bg=b;},D8=a=>{let b=new O();Eg(b,a);return b;},Fl=()=>{let b;CF=BA(0);b=new O;b.bg="";C$=b;C1=new BV;},B0=E(),Ex=E(B0),C6=null,ET=b=>{let c,d;if(!b)return 32;c
=0;d=b>>>16|0;if(d)c=16;else d=b;b=d>>>8|0;if(!b)b=d;else c=c|8;d=b>>>4|0;if(!d)d=b;else c=c|4;b=d>>>2|0;if(!b)b=d;else c=c|2;if(b>>>1|0)c=c|1;return (32-c|0)-1|0;},Fk=()=>{C6=BG(Cp);};
function Cf(){let a=this;D.call(a);a.bs=null;a.bp=0;}
let Cy=(a,b,c)=>{let d,e,f,g;if(b>=0&&b<=a.bp){if(c===null)c=J(2);else if(c.bg.length?0:1)return a;d=a.bp+c.bg.length|0;DT(a,d);e=a.bp-1|0;while(e>=b){a.bs.data[e+c.bg.length|0]=a.bs.data[e];e=e+(-1)|0;}a.bp=a.bp+c.bg.length|0;e=0;a:{while(e<c.bg.length){f=a.bs;g=b+1|0;if(e<0)break a;if(e>=c.bg.length)break a;f.data[b]=c.bg.charCodeAt(e);e=e+1|0;b=g;}return a;}c=new Ck;X(c);c.bn=1;c.bm=1;S(c);}c=new Ck;X(c);c.bn=1;c.bm=1;S(c);},DT=(a,b)=>{let c,d,e,f,g,h;c=a.bs.data;d=c.length;if(d>=b)return;if(d>=1073741823)e
=2147483647;else{f=d*2|0;e=5;if(f>e)e=f;if(b>e)e=b;}g=BA(e);if(e<d)d=e;h=g.data;b=0;while(b<d){h[b]=c[b];b=b+1|0;}a.bs=g;},Dp=E(0),CZ=E(Cf),D3=E(),Ev=E(),Ep=E(),Dc=E(),Bl=null,Bu=null,Bx=null,G=null,C2=null,N=null,Co=0,BZ=null,P=()=>{P=CN(Dc);E2();},Ej=b=>{let c,d,e,f,g,h,i,j;P();c=window;Bu=c;d=c.document;Bx=d;c=d.getElementById(BL(BZ));b=Bp(2);e=b.data;N=b;b=Bn.data;e[0]=b[0];e[1]=b[1];if(c===null)G=Dh(Bx.body);else if(!(c instanceof HTMLCanvasElement?1:0)){c.removeAttribute("id");G=Dh(c);if(c.hasAttribute("fullscreen")
?1:0){c.removeAttribute("fullscreen");G.setAttribute("fullscreen","");}}else{G=c;b=(CA(c)).data;if(b[0])N.data[0]=G.width;else G.width=N.data[0];if(b[1])N.data[1]=G.height;else G.height=N.data[1];}C2=G.getContext("2d");if(!(G.hasAttribute("fullscreen")?1:0))CR();else{G.removeAttribute("fullscreen");N.data[0]=Bu.innerWidth;N.data[1]=Bu.innerHeight;G.width=N.data[0];G.height=N.data[1];Bx.body.setAttribute("style","margin:0;overflow:hidden;height:100vh;width:100vw;");Co=1;f=G.hasAttribute("fullscreen-alt")?1:0;BO
=f;if(f)G.removeAttribute("fullscreen-alt");}c=new Df;d=G;g=C2;c.b4=d;c.bZ=g;h=new Dn;h.by=g;h.bC=d;c.bX=h;c.bl=Bp(32767);Bl=c;d=new Cl;g=null;d.br=new D;d.bv=1;d.bT=g;d.bD=c;i=BC;BC=i+1|0;d.bR=Ba(i);c=new Dq;c.bK=d;Fe(c);G.tabIndex=0;G.setAttribute("style","outline:none;border:none;image-rendering:pixelated;");G.focus();c=G;g=new B9;h="addEventListener";d="mousedown";j=!(g instanceof L)?g:g.bj;c[h](d,V(j,"handleEvent"));c=G;g=new B7;h="addEventListener";d="mouseup";j=!(g instanceof L)?g:g.bj;c[h](d,V(j,"handleEvent"));c
=G;g=new B8;h="addEventListener";d="mousemove";j=!(g instanceof L)?g:g.bj;c[h](d,V(j,"handleEvent"));c=G;g=new B5;h="addEventListener";d="mouseleave";j=!(g instanceof L)?g:g.bj;c[h](d,V(j,"handleEvent"));c=G;g=new B6;h="addEventListener";d="contextmenu";j=!(g instanceof L)?g:g.bj;c[h](d,V(j,"handleEvent"));c=G;g=new B3;h="addEventListener";d="keydown";j=!(g instanceof L)?g:g.bj;c[h](d,V(j,"handleEvent"));c=G;g=new B4;h="addEventListener";d="keyup";j=!(g instanceof L)?g:g.bj;c[h](d,V(j,"handleEvent"));c=Bu;g
=new B$;h="addEventListener";d="resize";j=!(g instanceof L)?g:g.bj;c[h](d,V(j,"handleEvent"));c=Bx;g=new B_;c.addEventListener("click",V(!(g instanceof L)?g:g.bj,"handleEvent"));},Dh=b=>{let c,d;P();c=Bx.createElement("canvas");d=BL(BZ);c.id=d;d=N.data[0];c.width=d;d=N.data[1];c.height=d;b.appendChild(c);return c;},CR=()=>{let b,c,d;P();b=CA(G);c=Bu.innerWidth;d=Bu.innerHeight;if(!(!Co&&b.data[0]&&c>=N.data[0])){G.width=c;N.data[0]=c;}if(!(!Co&&b.data[1]&&d>=N.data[1])){G.height=d;N.data[1]=d;}},DN=b=>{let c,
d,e;P();c=G;d=BY(c.width,c.height,b.offsetX,b.offsetY);c=new Bj;e=b.buttons>0?506:503;d=d.data;c.bt=e;c.bx=d[0];c.bw=d[1];Bt(Bl,c);},DD=b=>{let c,d;P();c=G;d=(BY(c.width,c.height,b.offsetX,b.offsetY)).data;c=new Bj;c.bt=502;c.bx=d[0];c.bw=d[1];c.bE=b.button!=2?0:4;Bt(Bl,c);b.preventDefault();},EI=b=>{let c,d;P();c=G;d=(BY(c.width,c.height,b.offsetX,b.offsetY)).data;c=new Bj;c.bt=501;c.bx=d[0];c.bw=d[1];c.bE=b.button!=2?0:4;Bt(Bl,c);b.preventDefault();},E2=()=>{let b;CF=BA(0);b=new O;b.bg="";C$=b;C1=new BV;C6
=BG(Cp);DQ();C5=BG(BX);Di=BK(Cm,128);Dx();BZ=J(3);},EX=E(),Ek=(b,c)=>{let d,e,f,g,h,i,j,k,l;if(!b)return J(4);d=1<<c;e=d-1|0;f=(((32-ET(b)|0)+c|0)-1|0)/c|0;g=BA(f);h=g.data;i=M(f-1|0,c);j=0;while(i>=0){k=j+1|0;h[j]=D0((b>>>i|0)&e,d);i=i-c|0;j=k;}l=new O;l.bg=Cd(g.data,0,h.length);return l;},DU=E(),E0=null,DL=null,Be=null,Bn=null,BO=0,BY=(b,c,d,e)=>{let f,g,h,i,j,k,l,m,n,o;if(!BO){f=Be.data;g=b/f[0]|0;h=c/f[1]|0;if(g>h)h=g;i=h;}else{f=Be.data;h=b/f[0]|0;g=c/f[1]|0;if(h<g)g=h;i=g;}j=Be.data[0]*i;h=Bk(Bi(j+Bq(j)
*0.5));j=Be.data[1]*i;g=Bk(Bi(j+Bq(j)*0.5));k=(b-h|0)/2|0;l=(c-g|0)/2|0;if(d>=k&&d<(k+h|0)&&e>=l&&e<(l+g|0)){j=(d-k|0)/h;m=(e-l|0)/g;i=j*Bn.data[0];n=Bk(Bi(i+Bq(i)*0.5));i=m*Bn.data[1];o=Bk(Bi(i+Bq(i)*0.5));if(n<0)n=0;else{f=Bn.data;if(n>(f[0]-1|0))n=f[0]-1|0;}if(o<0)o=0;else{f=Bn.data;if(o>f[1])o=f[1]-1|0;}return BN([n,o]);}return BN([(-1),(-1)]);},DQ=()=>{E0=J(5);DL=J(6);Be=BN([214,120]);Bn=BN([856,480]);BO=0;};
function B1(){let a=this;D.call(a);a.b4=null;a.bZ=null;a.bX=null;}
let EC=a=>{return 1;},EQ=a=>{return a.bX;},Cq=E(0);
function Df(){B1.call(this);this.bl=null;}
let Dz=a=>{let b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ba,bb,bc,bd,be,bf,bg,bh,bi,bj,bk,bl,bm,bn,bo,bp,bq,br,bs,bt,bu,bv,bw,bx,by,bz,bA,bB,bC,bD,bE,bF,bG,bH,bI,bJ,bK,bL,bM,bN,bO,bP,bQ,bR,bS,bT,bU,bV,bW,bX,bY,bZ,b0,b1,b2,b3,b4,b5,$$je,$p,$z;$p=0;if(Bh()){let $T=K();$p=$T.l();b5=$T.l();b4=$T.l();b3=$T.l();b2=$T.l();b1=$T.l();b0=$T.l();bZ=$T.l();bY=$T.l();bX=$T.l();bW=$T.l();bV=$T.l();bU=$T.l();bT=$T.l();bS=$T.l();bR=$T.l();bQ=$T.l();bP=$T.l();bO=$T.l();bN=$T.l();bM=$T.l();bL=$T.l();bK=$T.l();bJ=$T.l();bI
=$T.l();bH=$T.l();bG=$T.l();bF=$T.l();bE=$T.l();bD=$T.l();bC=$T.l();bB=$T.l();bA=$T.l();bz=$T.l();by=$T.l();bx=$T.l();bw=$T.l();bv=$T.l();bu=$T.l();bt=$T.l();bs=$T.l();br=$T.l();bq=$T.l();bp=$T.l();bo=$T.l();bn=$T.l();bm=$T.l();bl=$T.l();bk=$T.l();bj=$T.l();bi=$T.l();bh=$T.l();bg=$T.l();bf=$T.l();be=$T.l();bd=$T.l();bc=$T.l();bb=$T.l();ba=$T.l();z=$T.l();y=$T.l();x=$T.l();w=$T.l();v=$T.l();u=$T.l();t=$T.l();s=$T.l();r=$T.l();q=$T.l();p=$T.l();o=$T.l();n=$T.l();m=$T.l();l=$T.l();k=$T.l();j=$T.l();i=$T.l();h=
$T.l();g=$T.l();f=$T.l();e=$T.l();d=$T.l();c=$T.l();b=$T.l();a=$T.l();}_:while(true){switch($p){case 0:a:{try{b=Ds();c=DA(214,120,1);d=EG(Es(D5(c)));e=Bp(262144);D1(b,Ba(18295169));f=0;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}g=e.data;while(true){try{if(f>=262144)break;g[f]=((f/64|0)%64|0)<=(32+Bg(b,8)|0)?0:Bg(b,8)+1|0;f=f+1|0;continue;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{h=Bp(12288);i=1;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}
else{throw $$e;}}e=h.data;while(true){try{if(i>=16)break;j=255-Bg(b,96)|0;k=0;while(k<48){l=0;while(l<16){m=9858122;n=Y(i,4);if(!n)m=8355711;if(!(!n&&Bg(b,3)))j=255-Bg(b,96)|0;n=Y(i,1);if(!n&&k<((((M(l,l)*3|0)+(l*81|0)|0)>>2&3)+18|0))m=6990400;else if(!n&&k<((((M(l,l)*3|0)+(l*81|0)|0)>>2&3)+19|0))j=(j*2|0)/3|0;b:{if(i==7){c:{m=6771249;if(l>0&&l<15){if(k>0&&k<15)break c;if(k>32&&k<47)break c;}if(Bg(b,2))break b;j=M(j,150-((l&1)*100|0)|0)/100|0;break b;}m=12359778;o=l-7|0;p=(k&15)-7|0;if(o<0)o=1-o|0;if(p<0)p=
1-p|0;if(p<=o)p=o;j=(196-Bg(b,32)|0)+((p%3|0)*32|0)|0;}}if(i==5){m=11876885;if(!(((l+((k/4|0)*4|0)|0)%8|0)&&(k%4|0)))m=12365733;}n=k<32?j:j/2|0;if(i==8){m=5298487;if(!Bg(b,2)){m=0;n=255;}}n=(M(m>>16&255,n)/255|0)<<16|(M(m>>8&255,n)/255|0)<<8|(M(m&255,n)/255|0);e[(l+(k*16|0)|0)+((i*256|0)*3|0)|0]=n;l=l+1|0;}k=k+1|0;}i=i+1|0;continue;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{q=96.5;r=65.0;s=96.5;t=0.0;u=0.0;v=0.0;w=U();x=0;y=0.0;z=0.0;ba=y;bb=BF(ba);bc=BP(ba);ba=z;bd=BF(ba);be
=BP(ba);while(Ct(CW(U(),w),Ba(10))){h=a.bl.data;if(h[2]>0){bf=(h[2]-428|0)/214.0*2.0;bg=(h[3]-240|0)/120.0*2.0;bh=CU(bf*bf+bg*bg)-1.2000000476837158;if(bh<0.0)bh=0.0;if(bh>0.0){y=y+bf*bh/400.0;z=z-bg*bh/400.0;if(z<(-1.5700000524520874))z=(-1.5700000524520874);if(z>1.5700000524520874)z=1.5700000524520874;}}w=C3(w,Ba(10));h=a.bl.data;bf=0.0+(h[119]-h[115]|0)*0.019999999552965164;bg=0.0+(h[100]-h[97]|0)*0.019999999552965164;bh=t*0.5;bi=u*0.9900000095367432;bj=v*0.5;t=bh+bb*bf+bc*bg;v=bj+bc*bf-bb*bg;u=bi+0.003000000026077032;bk
=0;while(bk<3){bl=q+t*(((bk+0|0)%3|0)/2|0);bm=bk+1|0;bn=r+u*((bm%3|0)/2|0);bo=s+v*(((bk+2|0)%3|0)/2|0);bp=0;d:{e:{while(bp<12){bq=(bl+(bp>>0&1)*0.6000000238418579-0.30000001192092896|0)-64|0;br=(bn+((bp>>2)-1|0)*0.800000011920929+0.6499999761581421|0)-64|0;bs=(bo+(bp>>1&1)*0.6000000238418579-0.30000001192092896|0)-64|0;if(bq<0)break e;if(br<0)break e;if(bs<0)break e;if(bq>=64)break e;if(br>=64)break e;if(bs>=64)break e;if(g[(bq+(br*64|0)|0)+(bs*4096|0)|0]>0)break e;bp=bp+1|0;}break d;}if(bk!=1){bl=q;bn=r;bo
=s;}else if(h[32]>0&&u>0.0){h[32]=0;u=(-0.10000000149011612);bl=q;bn=r;bo=s;}else{u=0.0;bl=q;bn=r;bo=s;}}bk=bm;q=bl;r=bn;s=bo;}}h=a.bl.data;if(h[1]>0&&(-1)>0){g[(-1)]=0;h[1]=0;}if(h[0]>0&&(-1)>0){g[(-1)+x|0]=1;h[0]=0;}bt=0;while(bt<12){bu=(q+(bt>>0&1)*0.6000000238418579-0.30000001192092896|0)-64|0;bv=(r+((bt>>2)-1|0)*0.800000011920929+0.6499999761581421|0)-64|0;bw=(s+(bt>>1&1)*0.6000000238418579-0.30000001192092896|0)-64|0;if(bu>=0&&bv>=0&&bw>=0&&bu<64&&bv<64&&bw<64)g[(bu+(bv*64|0)|0)+(bw*4096|0)|0]=0;bt=bt
+1|0;}bx=(-1);by=0;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}bh=1.0*be;bl=1.0*bd;while(true){try{if(by>=214)break;bz=(by-107|0)/90.0;bA=0;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}bn=bz*bc;bB=bz*bb;while(true){try{if(bA>=120)break;bC=(bA-60|0)/90.0;bD=bh+bC*bd;bE=bC*be-bl;bF=bn+bD*bb;bG=bD*bc-bB;bH=0;bI=255;bJ=20.0;bK=5.0;bL=0;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}while(true){try{if(bL>=3)break;n=Y(bL,1);bf=n?bF:bE;l
=Y(bL,2);if(!l)bf=bG;k=Y(bf,0.0);if(k<0)bf= -bf;bM=1.0/bf;bN=bF*bM;bi=bE*bM;bj=bG*bM;bO=q-(q|0);if(!n)bO=r-(r|0);if(!l)bO=s-(s|0);if(k>0)bO=1.0-bO;bP=bM*bO;bQ=q+bN*bO;bR=r+bi*bO;bS=s+bj*bO;if(k<0){if(!bL)bQ=bQ-1.0;if(!n)bR=bR-1.0;if(!l)bS=bS-1.0;}}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}o=Y(bi,0.0);f:{try{while(true){ba=bP;if(ba>=bJ)break f;bT=(bQ|0)-64|0;bU=(bR|0)-64|0;bV=(bS|0)-64|0;if(bT<0)break f;if(bU<0)break f;if(bV<0)break f;if(bT>=64)break f;if(bU>=64)break f;if(bV>=64)break;bW
=(bT+(bU*64|0)|0)+(bV*4096|0)|0;bX=g[bW];if(bX>0){p=((bQ+bS)*16.0|0)&15;l=((bR*16.0|0)&15)+16|0;if(!n){p=(bQ*16.0|0)&15;l=(bS*16.0|0)&15;if(o<0)l=l+32|0;}g:{bY=16777215;if(bW==(-1)){if(p<=0)break g;j=l%16|0;if(j<=0)break g;if(p>=15)break g;if(j>=15)break g;}bY=e[(p+(l*16|0)|0)+((bX*256|0)*3|0)|0];}if(bP>=bK)bW=bx;else if(by!=(h[2]/4|0))bW=bx;else if(bA!=(h[3]/4|0))bW=bx;else{bZ=1;if(k>0)bZ=(-1);x=bZ<<(6*bL|0);bK=bP;}if(bY<=0)bx=bW;else{bI=M(255-(bP/20.0*255.0|0)|0,255-(((bL+2|0)%3|0)*50|0)|0)/255|0;bx=bW;bH
=bY;bJ=ba;}}bQ=bQ+bN;bR=bR+bi;bS=bS+bj;bP=bP+bM;}break f;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{bL=bL+1|0;continue;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{b0=d.data;b1=M(bH>>16&255,bI)/255|0;b2=M(bH>>8&255,bI)/255|0;b3=M(bH&255,bI)/255|0;b0[by+(bA*214|0)|0]=b1<<16|b2<<8|b3;bA=bA+1|0;continue;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{by=by+1|0;continue;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}
else{throw $$e;}}}try{b4=Ba(2);$p=1;continue _;}catch($$e){$$je=H($$e);if($$je instanceof I){}else{throw $$e;}}}return;case 1:a:{h:{try{DJ(b4);if(T()){break _;}b=a;if(EC(b))break h;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}return;}try{E4(EQ(b),c,0,0,856,480,null);b5=bx;ba=y;bb=BF(ba);bc=BP(ba);ba=z;bd=BF(ba);be=BP(ba);while(Ct(CW(U(),w),Ba(10))){h=a.bl.data;if(h[2]>0){bf=(h[2]-428|0)/214.0*2.0;bg=(h[3]-240|0)/120.0*2.0;bh=CU(bf*bf+bg*bg)-1.2000000476837158;if(bh<0.0)bh=0.0;if(bh
>0.0){y=y+bf*bh/400.0;z=z-bg*bh/400.0;if(z<(-1.5700000524520874))z=(-1.5700000524520874);if(z>1.5700000524520874)z=1.5700000524520874;}}w=C3(w,Ba(10));h=a.bl.data;bf=0.0+(h[119]-h[115]|0)*0.019999999552965164;bg=0.0+(h[100]-h[97]|0)*0.019999999552965164;bh=t*0.5;bi=u*0.9900000095367432;bj=v*0.5;t=bh+bb*bf+bc*bg;v=bj+bc*bf-bb*bg;u=bi+0.003000000026077032;bk=0;while(bk<3){bl=q+t*(((bk+0|0)%3|0)/2|0);bm=bk+1|0;bn=r+u*((bm%3|0)/2|0);bo=s+v*(((bk+2|0)%3|0)/2|0);bp=0;i:{j:{while(bp<12){bq=(bl+(bp>>0&1)*0.6000000238418579
-0.30000001192092896|0)-64|0;br=(bn+((bp>>2)-1|0)*0.800000011920929+0.6499999761581421|0)-64|0;bs=(bo+(bp>>1&1)*0.6000000238418579-0.30000001192092896|0)-64|0;if(bq<0)break j;if(br<0)break j;if(bs<0)break j;if(bq>=64)break j;if(br>=64)break j;if(bs>=64)break j;if(g[(bq+(br*64|0)|0)+(bs*4096|0)|0]>0)break j;bp=bp+1|0;}break i;}if(bk!=1){bl=q;bn=r;bo=s;}else if(h[32]>0&&u>0.0){h[32]=0;u=(-0.10000000149011612);bl=q;bn=r;bo=s;}else{u=0.0;bl=q;bn=r;bo=s;}}bk=bm;q=bl;r=bn;s=bo;}}h=a.bl.data;if(h[1]>0&&b5>0){g[b5]
=0;h[1]=0;}if(h[0]>0&&b5>0){g[b5+x|0]=1;h[0]=0;}bt=0;while(bt<12){bu=(q+(bt>>0&1)*0.6000000238418579-0.30000001192092896|0)-64|0;bv=(r+((bt>>2)-1|0)*0.800000011920929+0.6499999761581421|0)-64|0;bw=(s+(bt>>1&1)*0.6000000238418579-0.30000001192092896|0)-64|0;if(bu>=0&&bv>=0&&bw>=0&&bu<64&&bv<64&&bw<64)g[(bu+(bv*64|0)|0)+(bw*4096|0)|0]=0;bt=bt+1|0;}bx=(-1);by=0;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}bh=1.0*be;bl=1.0*bd;while(true){try{if(by>=214)break;bz=(by-107|0)/90.0;bA=0;}catch
($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}bn=bz*bc;bB=bz*bb;while(true){try{if(bA>=120)break;bC=(bA-60|0)/90.0;bD=bh+bC*bd;bE=bC*be-bl;bF=bn+bD*bb;bG=bD*bc-bB;bH=0;bI=255;bJ=20.0;bK=5.0;bL=0;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}while(true){try{if(bL>=3)break;n=Y(bL,1);bf=n?bF:bE;l=Y(bL,2);if(!l)bf=bG;k=Y(bf,0.0);if(k<0)bf= -bf;bM=1.0/bf;bN=bF*bM;bi=bE*bM;bj=bG*bM;bO=q-(q|0);if(!n)bO=r-(r|0);if(!l)bO=s-(s|0);if(k>0)bO=1.0-bO;bP=bM*bO;bQ=q+bN*bO;bR=r+
bi*bO;bS=s+bj*bO;if(k<0){if(!bL)bQ=bQ-1.0;if(!n)bR=bR-1.0;if(!l)bS=bS-1.0;}}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}o=Y(bi,0.0);k:{try{while(true){ba=bP;if(ba>=bJ)break k;bT=(bQ|0)-64|0;bU=(bR|0)-64|0;bV=(bS|0)-64|0;if(bT<0)break k;if(bU<0)break k;if(bV<0)break k;if(bT>=64)break k;if(bU>=64)break k;if(bV>=64)break;bW=(bT+(bU*64|0)|0)+(bV*4096|0)|0;bX=g[bW];if(bX>0){p=((bQ+bS)*16.0|0)&15;l=((bR*16.0|0)&15)+16|0;if(!n){p=(bQ*16.0|0)&15;l=(bS*16.0|0)&15;if(o<0)l=l+32|0;}l:{bY=16777215;if
(bW==b5){if(p<=0)break l;j=l%16|0;if(j<=0)break l;if(p>=15)break l;if(j>=15)break l;}bY=e[(p+(l*16|0)|0)+((bX*256|0)*3|0)|0];}if(bP>=bK)bW=bx;else if(by!=(h[2]/4|0))bW=bx;else if(bA!=(h[3]/4|0))bW=bx;else{bZ=1;if(k>0)bZ=(-1);x=bZ<<(6*bL|0);bK=bP;}if(bY<=0)bx=bW;else{bI=M(255-(bP/20.0*255.0|0)|0,255-(((bL+2|0)%3|0)*50|0)|0)/255|0;bx=bW;bH=bY;bJ=ba;}}bQ=bQ+bN;bR=bR+bi;bS=bS+bj;bP=bP+bM;}break k;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{bL=bL+1|0;continue;}catch($$e){$$je=H($$e);if
($$je instanceof I){break a;}else{throw $$e;}}}try{b0=d.data;b1=M(bH>>16&255,bI)/255|0;b2=M(bH>>8&255,bI)/255|0;b3=M(bH&255,bI)/255|0;b0[by+(bA*214|0)|0]=b1<<16|b2<<8|b3;bA=bA+1|0;continue;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{by=by+1|0;continue;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{b4=Ba(2);continue _;}catch($$e){$$je=H($$e);if($$je instanceof I){}else{throw $$e;}}}return;default:Bf();}}K().s(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,
t,u,v,w,x,y,z,ba,bb,bc,bd,be,bf,bg,bh,bi,bj,bk,bl,bm,bn,bo,bp,bq,br,bs,bt,bu,bv,bw,bx,by,bz,bA,bB,bC,bD,bE,bF,bG,bH,bI,bJ,bK,bL,bM,bN,bO,bP,bQ,bR,bS,bT,bU,bV,bW,bX,bY,bZ,b0,b1,b2,b3,b4,b5,$p);},Bt=(a,b)=>{let c,d;a:{b:{c:{c=0;switch(b.bt){case 401:c=1;break c;case 501:c=1;d=a.bl.data;d[2]=b.bx;d[3]=b.bw;break b;case 503:case 506:d=a.bl.data;d[2]=b.bx;d[3]=b.bw;break a;case 505:break;case 402:break c;case 502:break b;default:break a;}a.bl.data[2]=0;break a;}a.bl.data[b.bB]=c;break a;}if((b.bE&4)<=0)a.bl.data[0]
=c;else a.bl.data[1]=c;}return 1;},Bo=E(0),Z=E(0),B9=E(),EU=(b,c)=>{b;EI(c);};
function L(){D.call(this);this.bj=null;}
let CC=b=>{let c,d,e,f,g,h,i,j,k,l,m;if(b===null)return null;c=Bm(typeof b);if(c===J(7))d=1;else if(!(J(7) instanceof O))d=0;else{e=J(7);d=c.bg!==e.bg?0:1;}a:{if(!d){if(c===J(8))d=1;else if(!(J(8) instanceof O))d=0;else{e=J(8);d=c.bg!==e.bg?0:1;}if(!d){d=0;break a;}}d=1;}BB();e=CJ;if(e!==null){if(d){f=e.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=new L;h.bj=b;e.set(b,new WeakRef(h));return h;}if(c===J(9))d=1;else if(!(J(9) instanceof O))d=0;else{e=J(9);d=
c.bg!==e.bg?0:1;}if(d){i=BS;j=CH;f=i.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=new L;h.bj=b;k=h;i.set(b,new WeakRef(k));j.register(k,b);return h;}if(c===J(10))d=1;else if(!(J(10) instanceof O))d=0;else{e=J(10);d=c.bg!==e.bg?0:1;}if(d){l=BH;m=CQ;f=l.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=new L;h.bj=b;k=h;l.set(b,new WeakRef(k));m.register(k,b);return h;}if(c===J(11))d=1;else if(!(J(11) instanceof O))d
=0;else{e=J(11);d=c.bg!==e.bg?0:1;}if(d){f=Cv;g=f===null?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=new L;h.bj=b;Cv=new WeakRef(h);return h;}}e=new L;e.bj=b;return e;},B7=E(),DY=(b,c)=>{b;DD(c);},B8=E(),D6=(b,c)=>{b;DN(c);},B5=E(),Ez=(b,c)=>{b;P();b=new Bj;b.bt=505;Bt(Bl,b);},B6=E(),E9=(b,c)=>{b;P();c.preventDefault();},B3=E(),EE=(b,c)=>{let d;b;P();b=new Bj;b.bt=401;d=c.keyCode;if(d>=65&&d<=90)d=d+32|0;b.bB=d;Bt(Bl,b);c.preventDefault();},B4=E(),Dt=(b,c)=>{let d;b;P();b=new Bj;b.bt=402;d=c.keyCode;if
(d>=65&&d<=90)d=d+32|0;b.bB=d;Bt(Bl,b);c.preventDefault();},B$=E(),Ei=(b,c)=>{b;P();CR();},B_=E(),DI=(b,c)=>{b;P();G.focus();},EY=E(),CA=b=>{let c,d;c=ES(2);d=c.data;d[0]=0;d[1]=0;if(b.width)d[0]=1;if(b.height)d[1]=1;return c;},Ef=(b,c)=>{b.imageSmoothingEnabled=c;if(b.mozImageSmoothingEnabled!==undefined)b.mozImageSmoothingEnabled=c;if(b.webkitImageSmoothingEnabled!==undefined)b.webkitImageSmoothingEnabled=c;if(b.msImageSmoothingEnabled!==undefined)b.msImageSmoothingEnabled=c;},C_=E(0),BV=E(),Cm=E(),C5=null,Di
=null,D0=(b,c)=>{if(c>=2&&c<=36&&b>=0&&b<c)return b<10?(48+b|0)&65535:((97+b|0)-10|0)&65535;return 0;},Fj=()=>{C5=BG(BX);Di=BK(Cm,128);},DB=E();
function Dn(){let a=this;D.call(a);a.by=null;a.bC=null;}
let E4=(a,b,c,d,e,f,g)=>{let h,i,j,k,l,m,n,o;h=Bn.data;if(e==h[0]&&f==h[1]){i=a.bC.width;j=a.bC.height;k=DO(2).data;l=i;h=Be.data;k[0]=l/h[0];m=j;k[1]=m/h[1];n=!BO?D9(k[0],k[1]):E3(k[0],k[1]);o=Be.data[0]*n;e=Bk(Bi(o+Bq(o)*0.5));n=Be.data[1]*n;f=Bk(Bi(n+Bq(n)*0.5));c=(i-e|0)/2|0;d=(j-f|0)/2|0;a.by.clearRect(0.0,0.0,l,m);}DR(b);Ef(a.by,!!0);g=a.by;b=b.bz;m=c;l=d;n=e;o=f;g.drawImage(b,m,l,n,o);},BU=E(R);
function Cl(){let a=this;D.call(a);a.b1=null;a.bR=Dg;a.bo=Dg;a.br=null;a.bP=null;a.bA=null;a.bT=null;a.bv=0;a.bD=null;}
let BR=null,F=null,BC=0,Bb=0,C9=null,EB=a=>{let b,c,$$je,$p,$z;$p=0;if(Bh()){let $T=K();$p=$T.l();c=$T.l();b=$T.l();a=$T.l();}_:while(true){switch($p){case 0:a:{try{try{Bb=Bb+1|0;Dj(a);a.bA=E6();$p=1;continue _;}catch($$e){$$je=H($$e);if($$je instanceof By){b=$$je;}else{throw $$e;}}C0(Dr(a),a,b);break a;}catch($$e){$$je=H($$e);b=$$je;}c=a.br;$p=2;continue _;}b=a.br;$p=4;continue _;case 1:a:{b:{c:{try{Fc(a);if(T()){break _;}}catch($$e){$$je=H($$e);if($$je instanceof By){b=$$je;break c;}else{b=$$je;break b;}}b
=a.br;$p=3;continue _;}try{C0(Dr(a),a,b);break a;}catch($$e){$$je=H($$e);b=$$je;}}c=a.br;$p=2;continue _;}b=a.br;$p=4;continue _;case 2:BW(c);if(T()){break _;}a:{try{Cn(c);Br(c);break a;}catch($$e){$$je=H($$e);b=$$je;}Br(c);S(b);}a.bv=0;Bb=Bb-1|0;a.bA=null;c=BR;if(F!==c)F=c;F.bo=U();S(b);case 3:BW(b);if(T()){break _;}a:{try{Cn(b);Br(b);break a;}catch($$e){$$je=H($$e);c=$$je;}Br(b);S(c);}a.bv=0;Bb=Bb-1|0;a.bA=null;b=BR;if(F!==b)F=b;F.bo=U();return;case 4:BW(b);if(T()){break _;}a:{try{Cn(b);Br(b);break a;}catch
($$e){$$je=H($$e);c=$$je;}Br(b);S(c);}a.bv=0;Bb=Bb-1|0;a.bA=null;b=BR;if(F!==b)F=b;F.bo=U();return;default:Bf();}}K().s(a,b,c,$p);},Dj=b=>{if(F!==b)F=b;F.bo=U();},Fc=a=>{let b,$p,$z;$p=0;if(Bh()){let $T=K();$p=$T.l();b=$T.l();a=$T.l();}_:while(true){switch($p){case 0:b=a.bD;if(b===null)return;b=b;$p=1;case 1:Dz(b);if(T()){break _;}return;default:Bf();}}K().s(a,b,$p);},Dy=()=>{return F;},DJ=b=>{let $p,$z;$p=0;if(Bh()){let $T=K();$p=$T.l();b=$T.l();}_:while(true){switch($p){case 0:$p=1;case 1:El(b);if(T()){break _;}return;default:
Bf();}}K().s(b,$p);},DK=(b,c)=>{let d,e;d=F;e=new CT;e.bW=d;e.bV=c;e.b2=Ca(e,DH(b,Ba(2147483647))?2147483647:Bk(b));d.bP=e;},Dr=a=>{let b;b=a.b1;if(b!==null)return b;return C9;},Dx=()=>{let b,c,d;b=new Cl;c=null;b.br=new D;b.bv=1;b.bT=J(12);b.bD=c;d=BC;BC=d+1|0;b.bR=Ba(d);BR=b;F=b;BC=1;Bb=1;C9=new CY;},El=b=>{let thread=Cx();let javaThread=CO();if(thread.isResuming()){thread.status=0;let result=thread.attribute;if(result instanceof Error){throw result;}return result;}let callback=function(){};callback.e=val=>
{thread.attribute=val;BI(javaThread);thread.resume();};callback.be=e=>{thread.attribute=Cr(e);BI(javaThread);thread.resume();};callback=Dd(callback);thread.suspend(()=>{try {DK(b,callback);;}catch($e){callback.be($e);}});return null;};
function Ce(){let a=this;D.call(a);a.bt=0;a.bB=0;a.bx=0;a.bw=0;a.bE=0;}
let Bj=E(Ce),CD=E(0),CY=E(),C0=(a,b,c)=>{c.bb();},D2=E(),BF=b=>{return Math.sin(b);},BP=b=>{return Math.cos(b);},CU=b=>{return Math.sqrt(b);},Eb=()=>{return Math.random();},E3=(b,c)=>{return Math.min(b,c);},D9=(b,c)=>{return Math.max(b,c);},Bq=b=>{return Math.sign(b);},Bv=E(0);
function Dq(){D.call(this);this.bK=null;}
let EJ=a=>{let b,$p,$z;$p=0;if(Bh()){let $T=K();$p=$T.l();b=$T.l();a=$T.l();}_:while(true){switch($p){case 0:b=a.bK;$p=1;case 1:EB(b);if(T()){break _;}return;default:Bf();}}K().s(a,b,$p);},D7=E(),U=()=>{return Bi((new Date()).getTime());};
function BM(){let a=this;D.call(a);a.bq=null;a.bI=null;a.bh=null;a.bk=0;}
let BQ=E(R),Fg=E(),Cj=E(0),E_=E(0),Cz=E(R);
function CB(){D.call(this);this.bJ=null;}
let EA=a=>{D_(a.bJ);},E$=E(),Do=E(),Eq=null,CJ=null,BS=null,BH=null,Cv=null,CH=null,CQ=null,BB=()=>{BB=CN(Do);DV();},DV=()=>{let b;Eq=new WeakMap();CJ=!(typeof WeakRef!=='undefined'?1:0)?null:new WeakMap();BS=!(typeof WeakRef!=='undefined'?1:0)?null:new Map();BH=!(typeof WeakRef!=='undefined'?1:0)?null:new Map();if(BS===null)b=null;else{b=new Ci;b=new FinalizationRegistry(V(!(b instanceof L)?b:b.bj,"accept"));}CH=b;if(BH===null)b=null;else{b=new Ch;b=new FinalizationRegistry(V(!(b instanceof L)?b:b.bj,"accept"));}CQ
=b;},Eu=E(),C7=E(0);
function CI(){D.call(this);this.bu=null;}
let Dd=b=>{let c;c=new CI;c.bu=b;return c;},DW=(a,b)=>{a.bu.e(b);},Ff=(a,b)=>{a.bu.be(b);};
function Db(){let a=this;D.call(a);a.bN=null;a.bO=null;a.bL=0;a.bM=null;}
let DX=E(),Cc=E(0),Ci=E(),ER=(b,c)=>{b;BB();BS.delete(c);},Ch=E(),E5=(b,c)=>{b;BB();BH.delete(c);},Ck=E(BU),Dl=E(0),CG=E(),Ee=a=>{return;},Ds=()=>{let a=new CG();Ee(a);return a;},D1=(a,b)=>{return;},Bg=(a,b)=>{let c;if(b>0)return Eb()*b|0;c=new Cu;X(c);c.bn=1;c.bm=1;S(c);};
function Dm(){let a=this;D.call(a);a.b5=null;a.bz=null;a.bU=null;a.bH=null;a.bS=null;a.bQ=null;}
let EK=(a,b,c,d)=>{let e,f,g,h,i,j,k;e=Bp(2);f=e.data;a.b5=e;f[0]=b;f[1]=c;g=window.document.createElement("canvas");a.bz=g;h=b;g.width=h;i=a.bz;g=c;i.height=g;g=a.bz.getContext("2d");a.bU=g;j=b;k=c;h=g.createImageData(j,k);a.bH=h;g=new CE;g.bG=Bp(M(b,c));g.b0=h;a.bS=g;h=new Cw;h.bY=g;a.bQ=h;},DA=(a,b,c)=>{let d=new Dm();EK(d,a,b,c);return d;},D5=a=>{return a.bQ;},DR=a=>{let b,c,d,e,f,g,h,i,j;b=a.bH.data;c=a.bS.bG;d=0;e=0;while(true){f=c.data;if(d>=f.length)break;g=f[d];h=g>>16&255;b[e]=h;h=e+1|0;i=g>>8&255;b[h]
=i;h=e+2|0;g=g&255;b[h]=g;b[e+3|0]=255;d=d+1|0;e=e+4|0;}j=a.bU;b=a.bH;j.putImageData(b,0.0,0.0);};
function CE(){let a=this;D.call(a);a.bG=null;a.b0=null;}
let EG=a=>{return a.bG;};
function Cw(){D.call(this);this.bY=null;}
let Es=a=>{return a.bY;},Fd=E(),CK=E(0);
function CT(){let a=this;D.call(a);a.bW=null;a.bV=null;a.b6=0;a.b2=0;}
let Dv=a=>{let b,c;if(!a.b6){b=a.bW;b.bP=null;if(F!==b)F=b;F.bo=U();c=a.bV;b=null;c.bu.e(b);}},Cu=E(R);
Dw([]);
CV([D,0,0,[],0,3,0,0,0,Cs,0,D,[],3,3,0,0,0,CM,0,D,[],3,3,0,0,0,CL,0,D,[Cs,CM],4,3,0,0,0,Ec,0,D,[],4,3,0,0,0,EN,0,D,[],4,3,0,0,0,By,0,D,[],0,3,0,0,0,I,0,By,[],0,3,0,0,0,R,0,I,[],0,3,0,0,0,E8,0,R,[],0,3,0,0,0,Bz,0,D,[],3,3,0,0,0,BT,0,D,[],3,3,0,0,0,Cb,0,D,[],3,3,0,0,0,O,0,D,[Bz,BT,Cb],0,3,0,0,0,B0,0,D,[Bz],1,3,0,0,0,Ex,0,B0,[BT],0,3,0,0,0,Cf,0,D,[Bz,Cb],0,0,0,0,0,Dp,0,D,[],3,3,0,0,0,CZ,0,Cf,[Dp],0,3,0,0,0,D3,0,D,[],0,3,0,0,0,Ev,0,D,[],0,3,0,0,0,Ep,0,D,[],0,3,0,0,0,Dc,0,D,[],0,3,0,P,0,EX,0,D,[],4,3,0,0,0,DU,0,
D,[],0,3,0,0,0,B1,0,D,[],0,3,0,0,0,Cq,0,D,[],3,3,0,0,0,Df,0,B1,[Cq],0,3,0,0,0,Bo,0,D,[],3,3,0,0,0,Z,0,D,[Bo],3,3,0,0,0,B9,0,D,[Z],0,3,0,0,0,L,0,D,[],4,3,0,0,0,B7,0,D,[Z],0,3,0,0,0,B8,0,D,[Z],0,3,0,0,0,B5,0,D,[Z],0,3,0,0,0,B6,0,D,[Z],0,3,0,0,0,B3,0,D,[Z],0,3,0,0,0,B4,0,D,[Z],0,3,0,0,0,B$,0,D,[Z],0,3,0,0,0,B_,0,D,[Z],0,3,0,0,0,EY,0,D,[],0,3,0,0,0,C_,0,D,[],3,3,0,0,0,BV,0,D,[C_],0,3,0,0,0,Cm,0,D,[BT],0,3,0,0,0,DB,0,D,[],4,3,0,0,0,Dn,0,D,[],0,3,0,0,0,BU,0,R,[],0,3,0,0,0,Cl,0,D,[Cq],0,3,0,0,0,Ce,0,D,[],0,3,0,0,0,Bj,
0,Ce,[],0,3,0,0,0]);
CV([CD,0,D,[],3,3,0,0,0,CY,0,D,[CD],0,3,0,0,0,D2,0,D,[],4,3,0,0,0,Bv,0,D,[],3,3,0,0,0,Dq,0,D,[Bv],0,3,0,0,["o",B2(EJ)],D7,0,D,[],4,3,0,0,0,BM,0,D,[],0,0,0,0,0,BQ,0,R,[],0,3,0,0,0,Fg,0,D,[Bo],1,3,0,0,0,Cj,0,D,[],3,3,0,0,0,E_,0,D,[Bv,Cj],3,0,0,0,0,Cz,0,R,[],0,3,0,0,0,CB,0,D,[Bv],0,3,0,0,["o",B2(EA)],E$,0,D,[],4,3,0,0,0,Do,0,D,[],0,0,0,BB,0,Eu,0,D,[Bo],0,3,0,0,0,C7,0,D,[],3,3,0,0,0,CI,0,D,[C7],0,0,0,0,["e",CS(DW),"be",CS(Ff)],Db,0,D,[Bv],0,3,0,0,0,DX,0,D,[Bo],1,3,0,0,0,Cc,0,D,[Bo],3,0,0,0,0,Ci,0,D,[Cc],0,3,0,0,
0,Ch,0,D,[Cc],0,3,0,0,0,Ck,0,BU,[],0,3,0,0,0,Dl,0,D,[],3,3,0,0,0,CG,0,D,[Dl,Bz],0,3,0,0,0,Dm,0,D,[],0,3,0,0,0,CE,0,D,[],0,3,0,0,0,Cw,0,D,[],0,3,0,0,0,Fd,0,D,[],0,3,0,0,0,CK,0,D,[],3,3,0,0,0,CT,0,D,[Bv,Cj,CK],0,0,0,0,["o",B2(Dv)],Cu,0,R,[],0,3,0,0,0]);
let Ea=Bs(EZ),EF=Bs(BX),De=Bs(Cp),Et=Bs(Ed);
Ey(["Can\'t enter monitor from another thread synchronously","<java_object>@","null","game_frame","0","Minecraft 4k","4k","object","function","string","number","undefined","main"]);
O.prototype.toString=function(){return BL(this);};
O.prototype.valueOf=O.prototype.toString;D.prototype.toString=function(){return BL(EP(this));};
D.prototype.__teavm_class__=function(){return EH(this);};
let C=DE(Ej);
C.javaException=DM;
let Fm=Symbol('jsoClass');
(()=>{let c;c=B9.prototype;c.handleEvent=W(EU);c=B7.prototype;c.handleEvent=W(DY);c=B8.prototype;c.handleEvent=W(D6);c=B5.prototype;c.handleEvent=W(Ez);c=B6.prototype;c.handleEvent=W(E9);c=B3.prototype;c.handleEvent=W(EE);c=B4.prototype;c.handleEvent=W(Dt);c=B$.prototype;c.handleEvent=W(Ei);c=B_.prototype;c.handleEvent=W(DI);c=Ci.prototype;c.accept=W(ER);c=Ch.prototype;c.accept=W(E5);})();
B.main=C;}));
